[global]
# Fine-tune the hold vs tap delay (in milliseconds). 
# Uncomment and/or increase if you get accidental arrows while typing text quickly.
# overload_tap_timeout = 180

[ids]
04fe:0021

[main]
# --- Keys to the RIGHT of spacebar ---
# Maps the physical Japanese '変換' key to Right Meta (Super)
henkan = rightmeta
rightalt = rightcontrol

# --- Keys to the LEFT of spacebar ---
# Maps the physical Japanese '無変換' key to Left Meta (Super)
muhenkan = leftmeta

# Maps the physical Left "◇" key to Right Alt (AltGr / Option)
leftmeta = leftalt

# Hold semicolon for arrows, tap it for a regular semicolon
semicolon = overload(nav, semicolon)

[nav]
h = left
j = down
k = up
l = right
